### ISSUE TITLE
ESP32 BLEclient.ino issue

### ISSUE THREAD

**Issue by Goutham8128** [nkolban/esp32-snippets#198] opened 2017-11-14 06:58 UTC
Hi

I am using a sensor dongle which has sensor information in it. It is acting as a BLE server. I am using ESP32 acting as a BLE client module.I uploaded the BLE client code into the esp32 in Arduino IDE but after its execution it is just displaying the BLE server name and its service UUID. It is not able to read the characteristics of the BLE server. I want the BLE client(ESP32) to read the characteristics of the sensor dongle.
I have specified the Service UUID and specific characteristic UUID in the BLEclient.ino. But it is just reading the services but not able to display the sensor information inside the module(BLE server).

**Comment by chegewara** [comment] 2017-11-14 07:07
From this line https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino#L78, when serviceUUID equals service UUID advertised by your dongle, esp32 should have connect to your server dongle. There may be one issue, if dongle is advertising more than one service because at the moment getServiceUUID() returns only one advertised UUID and its the first found. You may try to change this line to connect if dongle name is recognized.

Just to be sure. You are using library from this repo and not from official esp32/arduino?

**Comment by Goutham8128** [comment] 2017-11-14 07:30
Hi

As you said the line 78 is same in my code and Dongle is advertising one service and exhibits 3 to 4 characteristics. I have mentioned the specific characteristic UUID in the code. though it is not connecting.
And i cloned the libraries from esp32/arduino only. Shouldn't i do this?

**Comment by chegewara** [comment] 2017-11-14 07:31
Can you paste some logs from serial output?

**Comment by Goutham8128** [comment] 2017-11-14 07:40
![screenshot from 2017-11-14 13-07-50](https://user-images.githubusercontent.com/24951213/32768271-2b79cf0a-c93d-11e7-8d76-e9f9634e655c.png)

**Comment by chegewara** [comment] 2017-11-14 07:44
Ok, now i assuming that you changed serviceUUID in BLE_client code to match that one from dongle, which is 0x2ea7. Can you try to use whole advertised serviceUUID as a string? its 00002ae7-.....

**Comment by Goutham8128** [comment] 2017-11-14 07:59
no I used the whole UUID
![screenshot from 2017-11-14 13-29-21](https://user-images.githubusercontent.com/24951213/32768935-e13bff1e-c93f-11e7-8c2b-194e2be6ce7d.png)

**Comment by chegewara** [comment] 2017-11-14 08:03
On the first screenshot serviceUUID looks different. Compare it and change in your code please.

**Comment by Goutham8128** [comment] 2017-11-14 09:44
The service UUID which is shown in the console window is not correct.Actually the service UUID which i mentioned in the code is correct, this I have verified with the Sensor dongle documentation.But when i upload the code to ESP-32 the console window is showing the different service UUID.How is it possible?
And when i run the BLEscan.ino code of arduino/esp32 library i have got the same output i.e the same service UUID which i have got in the output console of the BLEclient.ino.

**Comment by chegewara** [comment] 2017-11-14 09:47
This mean we have issue with library. Requires investigations. Be patience please and thank you for all provided info.

**Comment by Goutham8128** [comment] 2017-11-14 09:49
Sure and thanks for your guidance

**Comment by Goutham8128** [comment] 2017-11-15 11:07
Hi

![screennshottt](https://user-images.githubusercontent.com/24951213/32832874-02f9feba-ca23-11e7-85e3-ee29d9ee45e7.png)

i am using the arduino/esp32 library .I followed the procedure mentioned in Neil kolban's book for esp32. what do u mean by using this repo? Both libraries aren't same?

**Comment by chegewara** [comment] 2017-11-15 11:11
No they are not the same. Arduino library last time was updated about month ago and there has been made a lot changes and bug fixes since then. You may want to read this https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/ArduinoBLE.md

**Comment by Goutham8128** [comment] 2017-11-15 11:15
I have done this steps.The BLEclient.ino is compiled with no errors but not displaying the correct service UUID and not getting connected to the characteristics.So,What might be the problem for that?

**Comment by chegewara** [comment] 2017-11-15 11:18
This may be some issue with library, i will have to investigate this. I dont have this dongle,  but i will try to use second esp32 to emulate it.

**Comment by Goutham8128** [comment] 2017-11-15 11:21
OK. thank you.

issue with the BLEclient.h?

**Comment by chegewara** [comment] 2017-11-15 11:23
More like with BLEUUID, just guessing. Or RemoteService. There is few possibilities. Or maybe just BLEClient.ino

**Comment by Goutham8128** [comment] 2017-11-15 11:25
ok

**Comment by chegewara** [comment] 2017-11-15 12:20
Like i said, i dont have that dongle, but i did quick test with BLE_client connected to BLE_server and it works.  Here you can find listings ive been using to test https://github.com/chegewara/esp32-tests-library/tree/master/arduino/.

In your case you only need to change those lines to match your needs https://github.com/chegewara/esp32-tests-library/blob/master/arduino/BLE_client_uuid_advertising/BLE_client_uuid_advertising.ino#L12-L14

**Comment by Goutham8128** [comment] 2017-11-16 04:29
thank you. I will get back to you with the result.

**Comment by Goutham8128** [comment] 2017-11-16 05:04
Hi

I changed those two lines and added #define SERVICE_UUID and #define CHARACTERISTIC_UUID to my code but there is no change.It is displaying another service UUID and not getting connected to the characteristics.

Is this code only making two esp32's act as client and server or can i use other module as Server to send data to esp32?

**Comment by chegewara** [comment] 2017-11-16 05:08
Oh no, for sure you can use any module, any BLE peripheral to connect with esp32. Just there is some glitch i cant debug without device. Maybe @nkolban will have one and can help with this issue. Anyway, i will try something else later today.

**Comment by Goutham8128** [comment] 2017-11-16 05:13
ok.
Try to help me with this.Thank you.

**Comment by Goutham8128** [comment] 2017-11-17 06:28
![kolbnscrnshot](https://user-images.githubusercontent.com/24951213/32931973-ecf495ba-cb8c-11e7-9fd7-03354471bedc.png)

Hi
In Neil Kolban's book ,it is mentioned that the service UUID format is in the form of which i highlighted in the image. Only the first 2 bytes are needed to identify the type of service. So it is matched with the output in the serial monitor console i.e 0002ea7. So I think in the code the characteristic function is not getting executed it is getting stopped at the services loop.
So should I do any changes in the code to get connected to the characteristics of the BLE server?

**Comment by chegewara** [comment] 2017-11-17 06:53
Well known services are 16 bit, just like in your case https://github.com/nkolban/esp32-snippets/issues/198#issuecomment-344175281
BLE_client is nice example code. You have this line https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino#L81, and if its not printed in serial monitor then you need to move few lines back and check why. With help comes this line: https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino#L75
Like i said few days ago there is a difference between service UUID in your code, you said its service uuid from manual, and service UUID printed in serial monitor recognised by BLE scan.

Try to change this line https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino#L78

with this code:
`if (advertisedDevice.haveServiceUUID() && advertisedDevice.getServiceUUID().equals(BLEUUID((uint16_t)0x2ea7))) {`

**Comment by Goutham8128** [comment] 2017-11-17 07:43
Well, this is the output.Sensor is connected to the server but not getting connected to the characteristics.

![screenshot from 2017-11-17 12-39-48](https://user-images.githubusercontent.com/24951213/32936105-e8d64f76-cb98-11e7-8a3c-f4845d66a8eb.png)

**Comment by Goutham8128** [comment] 2017-11-17 07:48
I think just the Serial.print is getting executed not the main loop function.
because it is getting error as 0x003e which means connection is not established

**Comment by chegewara** [comment] 2017-11-17 07:48
Now you have to enumerate characteristics to see what UUID they have or using ie nRF on android device just check what characteristics UUID are. This is example how i am doing this. Of course you can always install this app https://github.com/nkolban/ESP32_Explorer and use its functionality to enumerate characteristics.

**Comment by chegewara** [comment] 2017-11-17 07:53
I missed one thing from this screenshot. There is no output from loop:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino#L115
or this 
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino#L118

**Comment by Goutham8128** [comment] 2017-11-17 07:56
We have 10 characteristics on this service 0x2ea7.Each characteristic is having individual 128bit UUID's  which we have verified with the nRFconnect. One of the characteristic UUID is  2ea78970-7d44-44bb-b097-26183f402401

**Comment by Goutham8128** [comment] 2017-11-17 07:59
And in the output window nothing is missed.We have not got output of either of that two lines 115 and 118. The line connected to server indicates the line 34 and 38 are printed but the main loop is not getting executed.If it does then the line 115 would get executed. I think the main loop is not getting executed.

**Comment by chegewara** [comment] 2017-11-17 08:01
The main loop is executed, just code cant pass thru this line https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino#L41

We can join iirs if you wish, will be faster to talk

**Comment by Goutham8128** [comment] 2017-11-17 08:04
yeah
Sure i will get back to you by 3pm.I came for lunch.Sorry for the delay.

**Comment by chegewara** [comment] 2017-11-17 08:06
Well, its 9 am. I have to get some sleep now.

**Comment by Goutham8128** [comment] 2017-11-17 09:34
ok

what is your time zone?

**Comment by chegewara** [comment] 2017-11-17 15:49
Whenever you are ready. Im online for next few hours

**Comment by nkolban** [comment] 2017-11-18 02:52
I'm checking in for duty as well.  Its thanks giving holidays for the next 9 days ... so ping on IRC in channel `#ESP32` if we can offer assistance.

**Comment by Goutham8128** [comment] 2017-11-18 05:06
![screenshot from 2017-11-18 10-35-34](https://user-images.githubusercontent.com/24951213/32977079-5c931e68-cc4c-11e7-8dc0-b5e70bc785e3.png)

**Comment by nkolban** [comment] 2017-11-18 05:15
Are you available for a link screen share/skype?  neil.kolban is my skype

**Comment by nkolban** [comment] 2017-11-18 20:49
I chatted extensively with the raiser.  We saw that the ESP32 is indeed receiving an indication that the UUID is 16bit however when looking at the advertisement through nRFConnect and through Linux, we see that it appears to be advertising a 128bit UUID.  The discrepancy is odd to say the least.  Our next plan is to have the user install the latest ESP-IDF and the latest version of the BLE libraries.  Then, with debugging on, run it again.  Assuming that the problem is still present, we will add some code to the library to dump (in hex) the advertising message and see what it looks like from a raw data perspective.  From there we should be able to manually walk through it and see what we find.

**Comment by chegewara** [comment] 2017-11-19 02:00
https://github.com/nkolban/esp32-snippets/issues/172#issuecomment-345485748

**Comment by Goutham8128** [comment] 2017-11-20 05:39
Hi
Thanks for the assistance.Sorry for the delay.I was engaged with some other work. I Checked that reference link which you have sent.
I will try and get back to you.

But I am able to get connected to the server only for the first time when you told me to change the code in line no 41 i.e assigning long UUID and in line no 78 short UUID. When i have done that changes it got connected but when i executed it again it is again the same case which i have told you earlier.

**Comment by Goutham8128** [comment] 2017-11-20 05:40
@nkolban  yeah sure we will connect on IRC when you get free time. I will plan accordingly.

**Comment by chegewara** [comment] 2017-11-20 05:43
@Goutham8128 No worries, there is no rush.

**Comment by Goutham8128** [comment] 2017-11-20 07:13
I am able to get connected to the server only for the first time when I changed the line 41(assigning short UUID) and line 78 (assigning Long UUID) as you told. When I did this server is connected only for the first time.the screenshot I have send above.Help me out with this.

**Comment by Goutham8128** [comment] 2017-11-21 04:38
Hi

Did u check out with this issue?

**Comment by chegewara** [comment] 2017-11-21 04:41
@Goutham8128 Can we join iirc?

**Comment by Goutham8128** [comment] 2017-11-21 04:42
yeah in 5 mins

**Comment by Goutham8128** [comment] 2017-11-21 04:58
![screenshot from 2017-11-18 10-35-34](https://user-images.githubusercontent.com/24951213/33055618-a9bab15e-cea6-11e7-89f0-0c7395171a1c.png)

**Comment by Goutham8128** [comment] 2017-11-21 05:09
![screenshot from 2017-11-21 10-38-45](https://user-images.githubusercontent.com/24951213/33055868-394cd620-cea8-11e7-8176-9d5b62f2646c.png)

**Comment by Goutham8128** [comment] 2017-11-21 05:24
![screenshot from 2017-11-21 10-51-56](https://user-images.githubusercontent.com/24951213/33056193-44fae366-ceaa-11e7-9664-86f11878f5f3.png)

**Comment by Goutham8128** [comment] 2017-11-23 06:18
Any updates ? @nkolban @chegewara

**Comment by chegewara** [comment] 2017-11-23 20:51
Ok, another idea. When you connect with esp32 to dongle and then disconnect, you cant connect again. But can you connect with nrfconnect? With different configurations:
1. connect with esp32, disconnect esp32 and try to connect android,
2. connect with nrfconnect hen disconnect and again try to connect with nrfconnect,
3. connect with nrfconnect, disconnect and try to connect with esp32.

More info and logs will give more chance to track issue.

**Comment by Goutham8128** [comment] 2017-11-27 04:54
I had done all the three cases.In 
Case1: After connecting with esp32 the dongle is still advertising .This I verified with nrfconnect as it is appearing in scan
Case2: Once connected with nrfconnect and after disconnecting we are succesfully getting reconnected to nrfconnect.
Case3:After connecting and disconnecting with nrfconnect , I tried to connect with esp32 but there is no change in the output as it is displaying "connected to server" and the UUID below in the output log.

**Comment by chegewara** [comment] 2017-11-27 05:01
1. yes, it is advertising, but did you try to connect with nrfconnect when esp32 is still connected?

3. as we know, esp32 can connect at least one time with no issue, the issue is when we try to connect second time. im trying to understand if this is the case when you reset all devices, then connect with nrfconnect and only nrfconnect, and then when nrfconnect is still connected, can you connect with esp32 that first time when it should connect with no issue

**Comment by nkolban** [comment] 2017-11-27 05:06
I ordered a dongle/device and am awaiting delivery for testing.

**Comment by Goutham8128** [comment] 2017-11-27 05:14
okay! When might be the delivery?

**Comment by nkolban** [comment] 2017-11-27 05:26
I believe I ordered on Tuesday ... this is Sunday ... assuming its coming from a domestic supplier and they have stock, I'd assume I should have it by this time next week.  I haven't seen any emails relating to shipment.

**Comment by Goutham8128** [comment] 2017-11-27 05:28
okay fine!

**Comment by nkolban** [comment] 2017-11-27 23:19
well shoot ... was going through issues and re-read this one.  I thought it "odd" that I hadn't received a confirmation receipt ... have gone back through my credit card history and there is no indication that I purchased the device.   I remember a conversation on IRC (that is now gone) where we speced out the identity of the device ... but I don't have that anymore.  Can you post back the identity of the device and I'll order another?

**Comment by nkolban** [comment] 2017-11-27 23:25
Okay ... found it:

https://www.mouser.com/ProductDetail/Dialog-Semiconductor/DA14583IOTSENSDNGL/?qs=sGAEpiMZZMvzWM6X48YRJD1x4Z6Y1PCOCKLqamhNUmQ%3d

I have now ordered and THIS time I got a positive confirmation by email ... so its on its way.  Lets imagine 10 days from today.

**Comment by nkolban** [comment] 2017-11-28 04:02
Received an email that it will arrive on or before December 6th.

**Comment by Goutham8128** [comment] 2017-11-28 04:58
okay !

**Comment by nkolban** [comment] 2017-11-30 17:53
Well that was super fast.  I received delivery today of the "dialog" device.  It may be the weekend before I can start testing against it ... but we are moving in the right direction.  I couldn't believe how big the box was that it came in.  It is about 2cm square but the box must have been about 50cm by 25cm.

**Comment by Goutham8128** [comment] 2017-11-30 17:55
Thats great! .

And yeah we are waiting for your test result.

**Comment by nkolban** [comment] 2017-12-01 03:37
Powered up the DA14583 IoT Sensor Dongle and the ESP32 found its BLE advertisement.  So far so good.  Now what I need to get my hands on are the descriptions of the services and characteristics exposed by the device.  Do we have a link to those?

**Comment by Goutham8128** [comment] 2017-12-01 04:41
[DA14583 IoT sensor reference application_UMB064.pdf](https://github.com/nkolban/esp32-snippets/files/1520421/DA14583.IoT.sensor.reference.application_UMB064.pdf)
[da14583_ds_3v0_sensor_dev_kit_Dialog_Semiconductor_Datasheet.pdf](https://github.com/nkolban/esp32-snippets/files/1520423/da14583_ds_3v0_sensor_dev_kit_Dialog_Semiconductor_Datasheet.pdf)
[DA14583_IoT_Sensor_Board_Schematic_design.pdf](https://github.com/nkolban/esp32-snippets/files/1520426/DA14583_IoT_Sensor_Board_Schematic_design.pdf)
[DA14583_IoT_sensor_UMB063_User_Manual.pdf](https://github.com/nkolban/esp32-snippets/files/1520428/DA14583_IoT_sensor_UMB063_User_Manual.pdf)
[UM-B-003_DA14580_581_583 Software Development Guide.pdf](https://github.com/nkolban/esp32-snippets/files/1520430/UM-B-003_DA14580_581_583.Software.Development.Guide.pdf)
[UM-B-065_Bluetooth_Smart_Communication_Interface_Board_.pdf](https://github.com/nkolban/esp32-snippets/files/1520432/UM-B-065_Bluetooth_Smart_Communication_Interface_Board_.pdf)
[Wearable reference design 285-01-F_BOM_DA14583.pdf](https://github.com/nkolban/esp32-snippets/files/1520436/Wearable.reference.design.285-01-F_BOM_DA14583.pdf)

**Comment by Goutham8128** [comment] 2017-12-01 04:46
https://support.dialog-semiconductor.com/

In the above link you can register and raise doubts here

**Comment by nkolban** [comment] 2017-12-01 05:41
I have run some more tests and almost immediately I can see that the DA14583 IoT Sensor Dongle isn't playing nicely.  Before I went anywhere near the ESP32, I wrote a JavaScript program that uses [noble](https://www.npmjs.com/package/noble) to list BLE devices, pick the one we want, connect to it and then list the services exposed on it.  The JavaScript app can be found here:

https://pastebin.com/L0dv1DJX

I tested the app against two devices.  One was the TI SensorTag and the other the Dialog DA14583 IoT Sensor Dongle.  With the TI SensorTag, everything worked perfectly.  Here is my output:

https://pastebin.com/2ug2rBEn

and here is the same output from the DA14583:

https://pastebin.com/ZqufMW0E

as you can see the TI SensorTag is found, connected and lists the exposed services while the DA14583 is also found, also able to be connected but fails to list its exposed services.

And of course, none of these tests are ESP32 related so that takes ESP32 out of the story and seems to point the finger at the DA14583.  Using my Android phone, I was able to list all the services exposed by the DA14583 ... so that is encouraging.  However, I/we are missing something about "normal" or "expected" connection protocols.  The expected workflow is:

1. Search for the advertised device and find its BD address.
2. Connect to the BD address
3. List the exposed services

This has always worked as described for all the BLE servers I have come across ... with now the exception of the DA14583.  I'm not going to test further with the DA14583 until I understand more why I can't connect from "noble".

Before I close this post ... while writing the above ... it dawned on me I could test with Linux "bluetoothctl".  I used that tool, scanned for the DA14583, found it, connected to it and then asked to list its services.  There they were as expected/desired.  So the mystery deepens.  It seems that "noble" is doing something wrong ... and now I need to see if ESP32 BLE C++ is doing the same ... wrong thing ... whatever that may be.

**Comment by Goutham8128** [comment] 2017-12-01 05:49
Ok.Thanks for your assistance.

any further research or any suggestion by you for us to do?.
We will also look into that ,our ultimate goal is to send dongle data to esp32 via BLE and the same to cloud using Wi-Fi.

**Comment by nkolban** [comment] 2017-12-01 15:13
The updates from yesterday were just my "End of day" report ... I am in US Central Time and that update was just my notes as I work along.   Obviously my focus is the ESP32.  The DA14583 (to me and just now) is merely a partner to the ESP32 and I bought one to try and assist you and others using similar.  However, what I now see is that the DA14583 is not an "off the shelf" dongle ... it is a full BLE MCU.   The troubles were are having with the "out of the box" DA14583 is as much likely a bad "sample program" running on the DA14583 as it could be anything.  That doesn't mean that DA14583 itself is bad, broken or otherwise in error ... but it could easily mean that the sample application that comes pre-installed on the IoT Dongle out of the box is not "brilliant" (possibility not fact).  If you are relying on the sample program for testing, that may be a bad idea.

Now that we have a non-ESP32 application that is failing (the "noble" based JavaScript program posted earlier) ... that should/could allow your own developers and Dialog itself to examine the puzzle in parallel.  If you do work on that or raise a ticket with Dialog ... please post links back here to this thread.  If you find a problem or someone has a clue, it would be a shame if we didn't share that knowledge to all investigators.

**Comment by Goutham8128** [comment] 2017-12-02 06:00
@nkolban pleasecheck this link. It was raised in Dialog support forum regrading DA14583 sensor dongle.
(https://support.dialog-semiconductor.com/comment/17221#comment-17221)
To view this you should login with your user id, pswd. If not registered please register.

**Comment by chegewara** [comment] 2017-12-02 06:16
Maybe im doing something wrong but i can read this post without registering/login

**Comment by Goutham8128** [comment] 2017-12-02 06:21
Yeah you can do that .No issue

**Comment by Goutham8128** [comment] 2017-12-04 06:53
Any updates @nkolban @chegewara ?.

Have you read the comments in the above link?

**Comment by Goutham8128** [comment] 2017-12-05 06:59
So, Do we need to do the changes in the code running in DA14583 dongle rather than code running in the ESP-32 module. ?? @chegewara @nkolban

**Comment by chegewara** [comment] 2017-12-05 07:18
Sorry but without device and without more data to analyze i cant do more.

**Comment by Goutham8128** [comment] 2017-12-05 07:21
ok..
yeah Mr.Kolban has the device.His interpretation was that code running on DA14583 is not perfect.So is there any application such that any sensor(other than DA14583) sends data to esp32 and later send the data to cloud.

**Comment by Goutham8128** [comment] 2017-12-08 05:07
Can u join me on irc @chegewara ?

**Comment by chegewara** [comment] 2017-12-08 05:08
Sure

**Comment by Goutham8128** [comment] 2017-12-08 05:09
I am unable to see you in #ESP32

**Comment by Goutham8128** [comment] 2017-12-11 07:32
@nkolban I am looking into the code of DA14583 sensor dongle. So should i do changes in the code running in the module.If so , any suggestion  or is it the esp32 code which I have to change but as you said it is the bad code running in DA14583 dongle.

**Closed** 2018-11-15 18:21 UTC
Labels: bug, waiting
